#!/usr/bin/env python3
"""Generate runtime SQL, service manifests and metadata for one resolved battery."""

from __future__ import annotations

import json
import re
import shlex
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

EXTENSION_NAME = re.compile(r"^[a-z][a-z0-9_]*$")
PROFILE_NAME = re.compile(r"^[a-z][a-z0-9_-]*$")
SERVICE_NAME = re.compile(r"^[a-z][a-z0-9_-]*$")
VALID_SERVICE_TYPES = {"python-http", "squid", "httpfs-minio", "postgres", "sqlserver"}
VALID_PREREQUISITES = {"google-bigquery"}


class BatteryError(ValueError):
    pass


def required_string(mapping: dict[str, Any], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value:
        raise BatteryError(f"{key} must be a non-empty string")
    return value


def write_init(path: Path, extensions: list[dict[str, str]], excluded: set[str]) -> None:
    lines = ["-- Generated from config/extensions.yml. Do not edit this file."]
    for extension in extensions:
        name = extension["name"]
        if name not in excluded:
            lines.append(f"LOAD {name};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def normalize_services(raw_services: Any, path: str) -> list[dict[str, Any]]:
    if not isinstance(raw_services, list):
        raise BatteryError(f"{path} must be a list")
    services: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, raw in enumerate(raw_services):
        if not isinstance(raw, dict):
            raise BatteryError(f"{path}[{index}] must be an object")
        name = required_string(raw, "name")
        service_type = required_string(raw, "type")
        if not SERVICE_NAME.fullmatch(name):
            raise BatteryError(f"{path}[{index}] has invalid service name {name}")
        if name in seen:
            raise BatteryError(f"{path} contains duplicate service {name}")
        if service_type not in VALID_SERVICE_TYPES:
            raise BatteryError(f"{path}[{index}] has unsupported type {service_type}")
        seen.add(name)
        services.append(dict(raw))
    return services


def normalize_prerequisites(raw: Any) -> list[dict[str, str]]:
    if not isinstance(raw, list):
        raise BatteryError("prerequisites must be a list")
    prerequisites: list[dict[str, str]] = []
    seen: set[str] = set()
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise BatteryError(f"prerequisites[{index}] must be an object")
        prerequisite_type = required_string(item, "type")
        if prerequisite_type not in VALID_PREREQUISITES:
            raise BatteryError(f"unsupported prerequisite: {prerequisite_type}")
        if prerequisite_type in seen:
            raise BatteryError(f"duplicate prerequisite: {prerequisite_type}")
        seen.add(prerequisite_type)
        prerequisites.append({"type": prerequisite_type})
    return prerequisites


def normalize_profiles(
    raw_profiles: Any,
    extensions: list[dict[str, str]],
    runner: str,
    output_dir: Path,
    battery_service_names: set[str],
) -> list[dict[str, Any]]:
    if not isinstance(raw_profiles, list) or not raw_profiles:
        raise BatteryError("profiles must be a non-empty list")
    resolved_names = {extension["name"] for extension in extensions}
    profiles: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, raw in enumerate(raw_profiles):
        if not isinstance(raw, dict):
            raise BatteryError(f"profiles[{index}] must be an object")
        name = required_string(raw, "name")
        if not PROFILE_NAME.fullmatch(name):
            raise BatteryError(f"invalid profile name: {name}")
        if name in seen:
            raise BatteryError(f"duplicate profile: {name}")
        seen.add(name)
        tests = required_string(raw, "tests")
        services = normalize_services(raw.get("services", []), f"profiles[{index}].services")
        overlap = battery_service_names & {service["name"] for service in services}
        if overlap:
            raise BatteryError(
                f"profile {name} duplicates battery service {sorted(overlap)[0]}"
            )
        if runner != "standard" and services:
            raise BatteryError(f"profile {name} services require the standard runner")
        raw_test_config = raw.get("testConfig")
        if runner == "standard" and not isinstance(raw_test_config, dict):
            raise BatteryError(f"profile {name} requires testConfig for the standard runner")

        normalized: dict[str, Any] = {
            "name": name,
            "tests": tests,
            "services": services,
        }
        excluded: set[str] = set()
        if raw_test_config is not None:
            if not isinstance(raw_test_config, dict):
                raise BatteryError(f"profile {name} testConfig must be an object")
            kind = required_string(raw_test_config, "kind")
            test_config: dict[str, Any] = {"kind": kind}
            if kind == "generated":
                raw_excluded = raw_test_config.get("excludedExtensions", [])
                raw_static = raw_test_config.get("staticallyLoadedExtensions")
                if not isinstance(raw_excluded, list):
                    raise BatteryError(f"profile {name} excludedExtensions must be a list")
                if not isinstance(raw_static, list) or not raw_static:
                    raise BatteryError(
                        f"profile {name} staticallyLoadedExtensions must be a non-empty list"
                    )
                for extension_name in raw_excluded:
                    if not isinstance(extension_name, str) or not EXTENSION_NAME.fullmatch(
                        extension_name
                    ):
                        raise BatteryError(
                            f"profile {name} contains an invalid excluded extension"
                        )
                    if extension_name not in resolved_names:
                        raise BatteryError(
                            f"profile {name} excludes unresolved extension {extension_name}"
                        )
                    excluded.add(extension_name)
                for extension_name in raw_static:
                    if not isinstance(extension_name, str) or not EXTENSION_NAME.fullmatch(
                        extension_name
                    ):
                        raise BatteryError(
                            f"profile {name} contains an invalid statically loaded extension"
                        )
                test_config["excludedExtensions"] = list(raw_excluded)
                test_config["staticallyLoadedExtensions"] = list(raw_static)
                description = raw_test_config.get("description")
                if description is not None:
                    if not isinstance(description, str) or not description:
                        raise BatteryError(f"profile {name} description must be a string")
                    test_config["description"] = description
            elif kind == "upstream":
                path = required_string(raw_test_config, "path")
                if path.startswith("/") or ".." in Path(path).parts:
                    raise BatteryError(
                        f"profile {name} upstream path must stay inside the checkout"
                    )
                test_config["path"] = path
            else:
                raise BatteryError(f"profile {name} has unsupported testConfig kind {kind}")
            normalized["testConfig"] = test_config

        init_name = f"init-profile-{name}.sql"
        write_init(output_dir / init_name, extensions, excluded)
        normalized["initScript"] = init_name
        (output_dir / f"profile-services-{name}.json").write_text(
            json.dumps(services, indent=2) + "\n", encoding="utf-8"
        )
        profiles.append(normalized)
    return profiles


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} BATTERY_JSON OUTPUT_DIR", file=sys.stderr)
        return 2

    source = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])
    try:
        battery = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(battery, dict):
            raise BatteryError("battery configuration must be a JSON object")

        name = required_string(battery, "name")
        runner = required_string(battery, "runner")
        pin = required_string(battery, "pin")
        duckdb_version = required_string(battery, "duckdbVersion")
        services = normalize_services(battery.get("services"), "services")
        prerequisites = normalize_prerequisites(battery.get("prerequisites"))
        capabilities = battery.get("capabilities")
        if not isinstance(capabilities, list) or not all(
            isinstance(item, str) and item for item in capabilities
        ):
            raise BatteryError("capabilities must be a list of strings")

        raw_extensions = battery.get("extensions")
        if not isinstance(raw_extensions, list) or not raw_extensions:
            raise BatteryError("extensions must be a non-empty list")

        extensions: list[dict[str, str]] = []
        seen: set[str] = set()
        for index, raw_extension in enumerate(raw_extensions):
            if not isinstance(raw_extension, dict):
                raise BatteryError(f"extensions[{index}] must be an object")
            extension_name = required_string(raw_extension, "name")
            if not EXTENSION_NAME.fullmatch(extension_name):
                raise BatteryError(f"invalid extension name: {extension_name}")
            if extension_name in seen:
                raise BatteryError(f"duplicate resolved extension: {extension_name}")
            seen.add(extension_name)
            normalized = {"name": extension_name}
            install_from = raw_extension.get("installFrom")
            if install_from is not None:
                if not isinstance(install_from, str) or not EXTENSION_NAME.fullmatch(install_from):
                    raise BatteryError(f"invalid installFrom for {extension_name}")
                normalized["installFrom"] = install_from
            extensions.append(normalized)

        output_dir.mkdir(parents=True, exist_ok=True)
        profiles = normalize_profiles(
            battery.get("profiles"),
            extensions,
            runner,
            output_dir,
            {service["name"] for service in services},
        )
        ignored_tests = battery.get("ignoredTests", [])
        if not isinstance(ignored_tests, list):
            raise BatteryError("ignoredTests must be a list")

        for filename, payload in (
            ("battery.json", battery),
            ("extensions.json", extensions),
            ("services.json", services),
            ("prerequisites.json", prerequisites),
            ("capabilities.json", capabilities),
            ("profiles.json", profiles),
        ):
            (output_dir / filename).write_text(
                json.dumps(payload, indent=2) + "\n", encoding="utf-8"
            )
        (output_dir / "profiles.tsv").write_text(
            "".join(f"{profile['name']}\t{profile['tests']}\n" for profile in profiles),
            encoding="utf-8",
        )

        install_lines = ["-- Generated from config/extensions.yml. Do not edit this file."]
        for extension in extensions:
            line = f"INSTALL {extension['name']}"
            if "installFrom" in extension:
                line += f" FROM {extension['installFrom']}"
            install_lines.append(line + ";")
        (output_dir / "install-extensions.sql").write_text(
            "\n".join(install_lines) + "\n", encoding="utf-8"
        )
        write_init(output_dir / "init-extensions.sql", extensions, set())

        global_ignored: list[tuple[str, str]] = []
        profile_ignored: dict[str, list[dict[str, str]]] = defaultdict(list)
        valid_profiles = {profile["name"] for profile in profiles}
        for index, ignored in enumerate(ignored_tests):
            if not isinstance(ignored, dict):
                raise BatteryError(f"ignoredTests[{index}] must be an object")
            test_path = required_string(ignored, "path")
            reason = required_string(ignored, "reason")
            profile_names = ignored.get("profiles", [])
            if not isinstance(profile_names, list):
                raise BatteryError(f"ignoredTests[{index}].profiles must be a list")
            if profile_names:
                for profile in profile_names:
                    if profile not in valid_profiles:
                        raise BatteryError(
                            f"ignoredTests[{index}] references unknown profile {profile}"
                        )
                    profile_ignored[profile].append({"path": test_path, "reason": reason})
            else:
                global_ignored.append((test_path, reason))

        (output_dir / "ignored-global.tsv").write_text(
            "".join(f"{path}\t{reason}\n" for path, reason in global_ignored),
            encoding="utf-8",
        )
        (output_dir / "profile-skips.json").write_text(
            json.dumps(profile_ignored, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        env_values = {
            "BATTERY_NAME": name,
            "RUNNER_KIND": runner,
            "TEST_FILTER": profiles[0]["tests"],
            "UPSTREAM_REF": pin,
            "DUCKDB_VERSION": duckdb_version,
        }
        (output_dir / "battery.env").write_text(
            "".join(f"{key}={shlex.quote(value)}\n" for key, value in env_values.items()),
            encoding="utf-8",
        )
        return 0
    except (OSError, json.JSONDecodeError, BatteryError) as exc:
        print(f"Invalid resolved battery configuration: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
