#!/usr/bin/env python3
"""Generate runtime SQL and metadata for one resolved test battery."""

from __future__ import annotations

import json
import re
import shlex
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

EXTENSION_NAME = re.compile(r"^[a-z][a-z0-9_]*$")


class BatteryError(ValueError):
    pass


def required_string(mapping: dict[str, Any], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value:
        raise BatteryError(f"{key} must be a non-empty string")
    return value


def write_init(path: Path, extensions: list[dict[str, str]], excluded: set[str]) -> None:
    lines = ["-- Generated from config/extensions.yml. Do not edit this file."]
    for extension in extensions:
        name = extension["name"]
        if name not in excluded:
            lines.append(f"LOAD {name};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} BATTERY_JSON OUTPUT_DIR", file=sys.stderr)
        return 2

    source = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])
    try:
        battery = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(battery, dict):
            raise BatteryError("battery configuration must be a JSON object")

        name = required_string(battery, "name")
        runner = required_string(battery, "runner")
        tests = required_string(battery, "tests")
        pin = required_string(battery, "pin")
        duckdb_version = required_string(battery, "duckdbVersion")
        setup = required_string(battery, "setup")

        raw_extensions = battery.get("extensions")
        if not isinstance(raw_extensions, list) or not raw_extensions:
            raise BatteryError("extensions must be a non-empty list")

        extensions: list[dict[str, str]] = []
        seen: set[str] = set()
        for index, raw_extension in enumerate(raw_extensions):
            if not isinstance(raw_extension, dict):
                raise BatteryError(f"extensions[{index}] must be an object")
            extension_name = required_string(raw_extension, "name")
            if not EXTENSION_NAME.fullmatch(extension_name):
                raise BatteryError(f"invalid extension name: {extension_name}")
            if extension_name in seen:
                raise BatteryError(f"duplicate resolved extension: {extension_name}")
            seen.add(extension_name)
            normalized = {"name": extension_name}
            install_from = raw_extension.get("installFrom")
            if install_from is not None:
                if not isinstance(install_from, str) or not EXTENSION_NAME.fullmatch(install_from):
                    raise BatteryError(f"invalid installFrom for {extension_name}")
                normalized["installFrom"] = install_from
            extensions.append(normalized)

        ignored_tests = battery.get("ignoredTests", [])
        if not isinstance(ignored_tests, list):
            raise BatteryError("ignoredTests must be a list")

        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "battery.json").write_text(
            json.dumps(battery, indent=2) + "\n", encoding="utf-8"
        )
        (output_dir / "extensions.json").write_text(
            json.dumps(extensions, indent=2) + "\n", encoding="utf-8"
        )

        install_lines = ["-- Generated from config/extensions.yml. Do not edit this file."]
        for extension in extensions:
            line = f"INSTALL {extension['name']}"
            if "installFrom" in extension:
                line += f" FROM {extension['installFrom']}"
            install_lines.append(line + ";")
        (output_dir / "install-extensions.sql").write_text(
            "\n".join(install_lines) + "\n", encoding="utf-8"
        )

        write_init(output_dir / "init-extensions.sql", extensions, set())
        write_init(output_dir / "init-without-httpfs.sql", extensions, {"httpfs"})
        write_init(
            output_dir / "init-ducklake-autoload.sql",
            extensions,
            {"httpfs", "postgres_scanner", "sqlite_scanner"},
        )
        write_init(output_dir / "init-without-mssql.sql", extensions, {"mssql"})

        global_ignored: list[tuple[str, str]] = []
        profile_ignored: dict[str, list[dict[str, str]]] = defaultdict(list)
        for index, ignored in enumerate(ignored_tests):
            if not isinstance(ignored, dict):
                raise BatteryError(f"ignoredTests[{index}] must be an object")
            test_path = required_string(ignored, "path")
            reason = required_string(ignored, "reason")
            profiles = ignored.get("profiles", [])
            if not isinstance(profiles, list):
                raise BatteryError(f"ignoredTests[{index}].profiles must be a list")
            if profiles:
                for profile in profiles:
                    if not isinstance(profile, str) or not profile:
                        raise BatteryError(f"ignoredTests[{index}] contains an invalid profile")
                    profile_ignored[profile].append({"path": test_path, "reason": reason})
            else:
                global_ignored.append((test_path, reason))

        (output_dir / "ignored-global.tsv").write_text(
            "".join(f"{path}\t{reason}\n" for path, reason in global_ignored),
            encoding="utf-8",
        )
        (output_dir / "profile-skips.json").write_text(
            json.dumps(profile_ignored, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        env_values = {
            "BATTERY_NAME": name,
            "RUNNER_KIND": runner,
            "TEST_FILTER": tests,
            "UPSTREAM_REF": pin,
            "DUCKDB_VERSION": duckdb_version,
            "SETUP_KIND": setup,
        }
        (output_dir / "battery.env").write_text(
            "".join(f"{key}={shlex.quote(value)}\n" for key, value in env_values.items()),
            encoding="utf-8",
        )
        return 0
    except (OSError, json.JSONDecodeError, BatteryError) as exc:
        print(f"Invalid resolved battery configuration: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
